### ISSUE TITLE
[Epic] Operator based on the Operator SDK

### ISSUE THREAD

**Issue by jasperchui** [janus-idp/operator#1]
## Goal

This epic aims to provide an operator based on Operator SDK that is releaseable and usable state where it offers a comparable stable experience as installing via helm chart.

## Acceptance criteria

- [ ] Operator is able to deploy Backstage
- [ ] Operator can reconcile changes
- [ ] Operator can enforce Janus IDP image
- [ ] Operator can enforce proper routing

## Requirements

- [ ] Test plan
- [ ] Documentation

## Roadmap
https://github.com/orgs/janus-idp/projects/5/views/1

## Notes

**Additional context**
Add any other context or screenshots about the epic here.

**Comment by rm3l** [comment]
/close

Closing as done.
