### ISSUE TITLE
Update README and documentation

### ISSUE THREAD

**Issue by rm3l** [janus-idp/operator#28]
/kind task

## Acceptance Criteria

- [x] How to develop on the Operator
- [x] How to deploy the Operator on both Kubernetes and OpenShift
- [x] ~Mention that the backend auth secret (introduced in https://github.com/janus-idp/operator/pull/27) takes precedence over any `backend.auth.keys` value from config files: https://github.com/janus-idp/operator/pull/27#discussion_r1404199791~ (no longer true)
- [x] Link to Custom Resource Definition fields and their descriptions
- [x] How to create Custom Resource with simple examples
- [x] How to use with external Database (https://github.com/janus-idp/operator/issues/8)
- [x] How to expose the Backstage Service on non-OpenShift clusters (https://github.com/janus-idp/operator/issues/13#issuecomment-1856061468)
- [x] Working under air-gapped/proxied environments (part of Admin doc) (https://github.com/janus-idp/operator/issues/80#issuecomment-1864733601)
- [ ] ...

**Comment by rm3l** [comment]
Partially implemented.

**Comment by rm3l** [comment]
/close

Closing as done.
