### ISSUE TITLE
[Epic] M1 functional scope

### ISSUE THREAD

**Issue by gazarenkov** [janus-idp/operator#3]
The context: [Backstage Operator notes](https://docs.google.com/document/d/1ejnDTZIFMOLPDPXcljqfVu4bcXW-9vhiItYkqgCAUYY)

Functional requirements of M1:

- [x] Use operator-sdk to generate the CRD and scaffolder the code.
- [x] Implement the reconciler logic
- [x] Operator performs initial installation/configuration of Backstage instance (update is out of scope).
- [x] Default configuration k8s Runtime Objects (Deployment, Service...) and AppConfigs
- [x] Custom configuration Runtime Objects (as k8s resources) and AppConfigs 
- [x] Tested with [Janus-IDP showcase](https://github.com/janus-idp/backstage-showcase) image
- [x] Tested on OpenShift with rhdh image
- [x] Tested with external database (requires https://github.com/janus-idp/operator/issues/8)

**Comment by gazarenkov** [comment]
Resolved as all sobtasks done
