### ISSUE TITLE
[Epic] M1 productization scope

### ISSUE THREAD

**Issue by gazarenkov** [janus-idp/operator#4]
- [x] Reasonable Test coverage #5
- [x] Basic Documentation included
- [x] GitHub CI configured
- [x] Operator Image on public Image Registry (Quay.io)
- [x] #7

**Comment by gazarenkov** [comment]
Close this issue and create a couple concrete documentation related issues instead.

Feel free to reopen it if needed
