### ISSUE TITLE
[Epic] Make sure the Operator is ready to deploy on OperatorHub

### ISSUE THREAD

**Issue by gazarenkov** [janus-idp/operator#7]
Bundle: https://sdk.operatorframework.io/docs/olm-integration/quickstart-bundle/#creating-a-bundle
Community Operator: https://github.com/k8s-operatorhub

- [x] https://github.com/janus-idp/operator/issues/9
- [x] Make sure we can deploy and run everything in our own cluster
- [ ] ~PR to submit to Community Operators (can take at least 2 weeks to get reviewed and merged)~ (not the priority right now)

**Comment by rm3l** [comment]
Closing this issue as done..
As we discussed already, for now, the priority is to have the Operator available on the downstream catalog, which should be already possible (thanks to RHIDP-488). So the Operator is ready to deploy on OperatorHub at this point.
We'll see later if we need to publish to the community Operator Hub. But this will be addressed as a separate issue.
